spring:
  application:
    name: service-item

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000


logging:
  level:
    com:
      shiro: debug
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p})  %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 8002

